version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        volumes:
            - /var/lib/rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        env_file:
            - .env

    auth:
        build:
            context: ./
            dockerfile: ./apps/auth/Dockerfile
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - postgres_auth
        volumes:
            - .:/usr/src/app # любые изменения в основной директории должны отражаться на состоянии контейнера
            - /usr/src/app/node_modules # Эти изменения не будут отражаться
        command: npm run start:dev auth # Перезаписывает CMD в Dockerfile. На боевом сервере нужна более специфичнаяя команда

    profiles:
        build:
            context: ./
            dockerfile: ./apps/profiles/Dockerfile
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - postgres_profiles
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev profiles

    api:
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        ports:
            - '4000:5000'
        env_file:
            - .env
        depends_on:
            - rabbitmq
            - auth
            - profiles
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev api

    postgres_auth:
        image: postgres
        env_file:
            - .env
        ports:
            - "5435:5432"
        volumes:
            - ./db/data_auth:/var/lib/postgresql/data
    
    postgres_profiles:
        image: postgres
        env_file:
            - .env
        ports:
            - '5434:5432'
        volumes:
            - ./db/data_profiles:/var/lib/postgresql/data

    postgres_admin:
        image: dpage/pgadmin4
        depends_on:
            - postgres_auth
            - postgres_profiles
        env_file:
            - .env
        ports:
            - '15432:80'